version: '3.9'
services:
  db:
    image: mysql:8.0.31
    container_name: map_market_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: map_market_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - map-market-network
      
  map-market_backend:
    image: vaiento/map-market
    container_name: map_market_app
    restart: always
    build: ./application
    working_dir: /application
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/map_market_db?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - map-market-network
      
networks:
  map-market-network:
    name: map-market-network
    driver: bridge
