security:
    jwt:
        token:
            secret-key: 53ccr37
            expire-length: 3600000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/map_market
        username: root
        password: 1234567
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: none
        show-sql: false

flyway:
    enabled: true
    locations: classpath:db.migration