name: Continuous Integration to docker hub

on:
  push:
    branches:
      - main
      - devAplicacao
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./application
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: 
        docker tag ${{ secrets.DOCKER_USERNAME }}/MapMarket  ${{ secrets.DOCKER_USERNAME }}/MapMarket:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/MapMarket:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/MapMarket:latest
